/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 */
plugins {
    kotlin("jvm") version("1.9.24") apply(false)
    kotlin("plugin.jpa") version("1.9.24") apply(false)
    kotlin("plugin.spring") version("1.9.24") apply(false)
    id("org.springframework.boot") version("3.3.1") apply(false)
    id("io.spring.dependency-management") version("1.1.5") apply(false)
}

version = "1.0.0"
group = "com.fussionlabs"

subprojects {
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

