spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin
      roles: USER

kafka:
  bootstrap-servers: localhost:9092
